# Contract Explainer - Development Docker Compose
# Simplified configuration for local development

version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: contract-explainer-dev
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    restart: unless-stopped

volumes:
  uploads_data: