# Contract Explainer - Docker Compose Configuration
# For local development and production deployment

version: '3.8'

services:
  web:
    build: .
    container_name: contract-explainer-web
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Redis for caching (optional for future scaling)
  redis:
    image: redis:7-alpine
    container_name: contract-explainer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: contract-explainer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped

volumes:
  uploads_data:
  redis_data: